services:
  taskapp:
    image: minat0/taskapp:latest
    # Uncomment to build locally
    #
    # build:
    #  context: ..
    #  dockerfile: "./docker/Dockerfile"
    #  args:
    #    IMAGE: "taskapp"
    #    VERSION: "latest"
    container_name: "TaskApp-fpm"
    depends_on:
      - db
    env_file: '.env.prod'
    volumes:
      - taskapp_data:/var/www/html
      - ./.env.prod:/var/www/html/.env
    networks:
      - tasknetwork

  nginx:
    image: nginx:latest
    container_name: "TaskApp-nginx"
    ports:
      - "8000:80"
    volumes:
      - taskapp_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - taskapp
    networks:
      - tasknetwork

  db:
    image: mysql:8.0
    container_name: "TaskApp-db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tasknetwork

networks:
  tasknetwork:
    driver: bridge

volumes:
  taskapp_data:
  mysql_data:
